UnitWorksCCS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UnitWorksCCS.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Dashboard()
        {
            Session["Errors"] = "";
            return View();
        }
    }
}

UnitWorksCCS/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnitWorksCCS.Models;
using System.Data.Entity;

namespace UnitWorksCCS.Controllers
{
    public class RolesController : Controller
    {
        i_facility_talEntities db = new i_facility_talEntities();
        // GET: Roles
        public ActionResult Index()
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.UserName = Session["Username"];
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            RolesModel Ra = new RolesModel();
            tblrole ro = new tblrole();
            Ra.Role = ro;
            Ra.RoleList = db.tblroles.Where(m => m.IsDeleted == 0);
            return View(Ra);
                
        }

        public ActionResult Create()
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }

            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            return View();
        }


        [HttpPost]
        public ActionResult Create(RolesModel tblrole)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            var DuplicateRole = db.tblroles.Where(m => m.IsDeleted == 0 && m.RoleDesc == tblrole.Role.RoleDesc).FirstOrDefault();
            if (DuplicateRole == null)
            {
                //  Update Role data with other required fields.
                int UserID = Convert.ToInt32(Session["UserId"]);
                tblrole.Role.CreatedBy = UserID;
                tblrole.Role.CreatedOn = System.DateTime.Now;
                tblrole.Role.IsDeleted = 0;

                using (i_facility_talEntities db = new i_facility_talEntities())
                {
                    db.tblroles.Add(tblrole.Role);
                    db.SaveChanges();
                }
            }
            else
            {
                Session["Error"] = "Duplicate Role : " + tblrole.Role.RoleDesc;
                return View(tblrole);
            }

            return RedirectToAction("Index");
        }

        //Edit Existing Role.
        [HandleError(View = "~/Views/Shared/Error.cshtml")]

        public ActionResult Edit(int id)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            //id = -1;
            using (i_facility_talEntities db = new i_facility_talEntities())
            {
                tblrole tblrole = db.tblroles.Find(id);
                //if (tblrole == null)
                //{
                //    //return HttpNotFound();
                //}
                int a = tblrole.Role_ID;
                return View(tblrole);
            }
        }
        [HttpPost]
        public ActionResult Edit(RolesModel tblrole)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }

            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            int UserID = Convert.ToInt32(Session["UserID"]);

            // Update Role data with other required fields.
            //tblrole.ModifiedBy = UserID;
            //tblrole.ModifiedOn = System.DateTime.Now;
            var DuplicateRole = db.tblroles.Where(m => m.IsDeleted == 0 && m.RoleDesc == tblrole.Role.RoleDesc && m.Role_ID != tblrole.Role.Role_ID).FirstOrDefault();
            if (DuplicateRole == null)
            {
                if (ModelState.IsValid)
                {
                    using (i_facility_talEntities db = new i_facility_talEntities())
                    {
                        var RoleData = db.tblroles.Find(tblrole.Role.Role_ID);
                        RoleData.RoleDesc = tblrole.Role.RoleDesc;
                        RoleData.RoleDesc = tblrole.Role.RoleDesc;
                        RoleData.RoleDesc = tblrole.Role.RoleDesc;
                        RoleData.ModifiedBy = 1;
                        RoleData.ModifiedOn = DateTime.Now;
                        db.Entry(RoleData).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
            }
            else
            {
                Session["Error"] = "Duplicate Role : " + tblrole.Role.RoleDesc;
                return View(tblrole);
            }
            return View(tblrole);
        }

        //Update IsDeleted = 1 i.e If IsDeleted=1 then its deleted row
        public ActionResult Delete(int id)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }

            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            int UserID1 = id;

            using (i_facility_talEntities db = new i_facility_talEntities())
            {
                tblrole tblrole = db.tblroles.Find(id);
                tblrole.IsDeleted = 1;
                tblrole.ModifiedBy = UserID1;
                tblrole.ModifiedOn = DateTime.Now;

                db.Entry(tblrole).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public JsonResult GetRoleById(int Id)
        {
            var Data = db.tblroles.Where(m => m.Role_ID == Id).Select(m => new { rolename = m.RoleDesc, roledesc = m.RoleDesc, roledisplay = m.RoleDesc });

            return Json(Data, JsonRequestBehavior.AllowGet);
        }
    }
}

UnitWorksCCS/Controllers/UserController.cs
using I_Facility.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using UnitWorksCCS;
using UnitWorksCCS.Models;

namespace I_Facility.Controllers
{
    public class UserController : Controller
    {
        i_facility_talEntities db = new i_facility_talEntities();

        public ActionResult Redirect()
        {
            return RedirectToAction("Login", "Login", null);
        }

        public ActionResult UserManagement()
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewData["roles"] = new SelectList(db.tblroles.Where(m => m.IsDeleted == 0), "Role_Id", "RoleDesc").ToList();

            return View();
        }

        public string GetUserMenus()
        {
            List<UserMenus> menus = new List<UserMenus>();
            string res = "";

            DataTable dt = new DataTable();
            try
            {
                using (MsqlConnection mc = new MsqlConnection())
                {
                    using (SqlCommand cmd = new SqlCommand("GetUserMenus", mc.sqlConnection))
                    {
                        using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                        {
                            mc.open();
                            cmd.CommandType = CommandType.StoredProcedure;
                            sda.Fill(dt);
                            mc.close();
                        }
                    }
                }
            }
            catch (Exception ex) { }


            for (int i = 0; i < dt.Rows.Count; i++)
            {
                UserMenus menu = new UserMenus();

                menu.Id = dt.Rows[i]["MenuName"].ToString();
                menu.MenuId = Convert.ToInt32(dt.Rows[i]["Id"]);
                menu.MenuName = dt.Rows[i]["MenuName"].ToString();

                menus.Add(menu);
            }

            res = JsonConvert.SerializeObject(menus);

            return res;
        }

        public string GetCheckboxesForUser(int roleId)
        {
            List<UserMenus> menus = new List<UserMenus>();
            string res = "";

            DataTable dt = new DataTable();
            try
            {
                using (MsqlConnection mc = new MsqlConnection())
                {
                    using (SqlCommand cmd = new SqlCommand("GetCheckboxesForUser", mc.sqlConnection))
                    {
                        using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                        {
                            mc.open();
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@roleId", roleId);
                            sda.Fill(dt);
                            mc.close();
                        }
                    }
                }
            }
            catch (Exception ex) { }

            for (int i = 0; i < dt.Rows.Count; i++)
            {
                UserMenus menu = new UserMenus();

                menu.Id = dt.Rows[i]["MenuName"].ToString();
                menu.MenuId = Convert.ToInt32(dt.Rows[i]["MenuId"]);
                menu.MenuName = dt.Rows[i]["MenuName"].ToString();

                string status = Convert.ToString(dt.Rows[i]["MenuStatus"]);
                menu.MenuStatus = status;

                menus.Add(menu);
            }

            res = JsonConvert.SerializeObject(menus);

            return res;
        }

        public string UpdateMenus(int roleId, string menuIds, string unMenuIds)
        {
            string res = "";

            if (menuIds != null)
            {
                menuIds = menuIds.Replace("[", "");
                menuIds = menuIds.Replace("]", "");
                menuIds = menuIds.Replace("\"", "");
                string[] menus = menuIds.Split(',');

                if (!menus.Contains(""))
                {
                    foreach (var item in menus)
                    {
                        int menuId = Convert.ToInt32(item);
                        var userMenu = db.user_menus.Where(m => m.IsDeleted == 0 && m.RoleId == roleId && m.MenuId == menuId).FirstOrDefault();
                        if (userMenu == null)
                        {
                            user_menus userMenus = new user_menus();
                            userMenus.RoleId = roleId;
                            userMenus.MenuId = menuId;
                            userMenus.MenuStatus = true;
                            userMenus.IsDeleted = 0;
                            db.user_menus.Add(userMenus);
                            db.SaveChanges();

                            TempData["toaster_success"] = "Menu Items Added Successfully";
                        }
                        else
                        {
                            userMenu.MenuStatus = true;
                            db.SaveChanges();

                            TempData["toaster_success"] = "Menu Items Updated Successfully";
                        }
                    }
                }
            }

            if (unMenuIds != null)
            {
                unMenuIds = unMenuIds.Replace("[", "");
                unMenuIds = unMenuIds.Replace("]", "");
                unMenuIds = unMenuIds.Replace("\"", "");
                string[] unMenus = unMenuIds.Split(',');

                if (!unMenus.Contains(""))
                {
                    foreach (var item in unMenus)
                    {
                        int unMenuId = Convert.ToInt32(item);
                        var userMenu = db.user_menus.Where(m => m.IsDeleted == 0 && m.RoleId == roleId && m.MenuId == unMenuId).FirstOrDefault();
                        userMenu.MenuStatus = false;
                        db.SaveChanges();

                        TempData["toaster_success"] = "Menu Items Updated Successfully";
                    }
                }
            }

            return res;
        }

        public string GetSideMenubar()
        {
            int roleId = Convert.ToInt32(Session["RoleID"]);

            string res = "";

            List<SideMenubar> sideMenubars = new List<SideMenubar>();

            DataTable dt = new DataTable();
            try
            {
                using (MsqlConnection mc = new MsqlConnection())
                {
                    using (SqlCommand cmd = new SqlCommand("GetSideMenubar", mc.sqlConnection))
                    {
                        using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                        {
                            mc.open();
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@roleId", roleId);
                            sda.Fill(dt);
                            mc.close();
                        }
                    }
                }
            }
            catch (Exception ex) { }

            for (int i = 0; i < dt.Rows.Count; i++)
            {
                int menuId = Convert.ToInt32(dt.Rows[i]["MenuId"]);

                SideMenubar sideMenubar = new SideMenubar();

                sideMenubar.MenuName = dt.Rows[i]["MenuName"].ToString();
                sideMenubar.RoleId = roleId;

                var imageurl = db.sidebar_menus.Where(m => m.MenuName == sideMenubar.MenuName).Select(m => m.ImageURL).FirstOrDefault();
                sideMenubar.ImageURL = imageurl;

                var values = db.sidebar_menus.Where(m => m.SubMenuName != null && m.MenuId == menuId && m.IsDeleted == 0).OrderBy(m => m.id).Select(m => new { m.SubMenuName, m.SubMenuURL }).ToList();

                if (values.Count == 0)
                {
                    //sideMenubar.MenuURL = dt.Rows[i]["MenuURL"].ToString();
                    var menuurl = db.sidebar_menus.Where(m => m.MenuName == sideMenubar.MenuName).Select(m => m.MenuURL).FirstOrDefault();
                    sideMenubar.MenuURL = menuurl;
                }
                List<SubMenus> subMenusList = new List<SubMenus>();
                foreach (var item in values)
                {
                    SubMenus subMenus = new SubMenus();

                    subMenus.SubMenuName = item.SubMenuName;
                    subMenus.SubMenuURL = item.SubMenuURL;

                    subMenusList.Add(subMenus);
                }

                sideMenubar.SubMenus = subMenusList;
                sideMenubars.Add(sideMenubar);
            }
            res = JsonConvert.SerializeObject(sideMenubars);

            return res;
        }

        public string GetDashboardMenus()
        {

            string res = "";
            int roleId = Convert.ToInt32(Session["RoleID"]);

            List<DashboardMenu> dashboardMenus = new List<DashboardMenu>();

            DataTable dt = new DataTable();
            try
            {
                using (MsqlConnection mc = new MsqlConnection())
                {
                    using (SqlCommand cmd = new SqlCommand("GetDashboardMenus", mc.sqlConnection))
                    {
                        using (SqlDataAdapter sda = new SqlDataAdapter(cmd))
                        {
                            mc.open();
                            cmd.CommandType = CommandType.StoredProcedure;
                            cmd.Parameters.AddWithValue("@roleId", roleId);
                            sda.Fill(dt);
                            mc.close();
                        }
                    }
                }
            }
            catch (Exception ex) { }

            for (int i = 0; i < dt.Rows.Count; i++)
            {
                DashboardMenu dashboardMenu = new DashboardMenu();

UnitWorksCCS/Views/Dashboard/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- page content -->
<div class="right_col" role="main">

    <div class="xx_panel">
        <div class="xx_content">
            <input type="hidden" id="hdnSession" data-value="@Request.RequestContext.HttpContext.Session["UserId"]" />
        </div>
        <div class="example-box-wrapper dashboardmenu">
            @* <div class="row">
                    <div class="col-md-3">
                        <a href="@Url.Action("Index", "MachineStatus" )" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-blue">
                                <div class="tile-header">
                                    Machine Status

                                </div>
                                <div class="tile-content-wrapper">

                                    <img src="~/images/machine-status.png" />
                                </div>
                                <div>
                                    <div class="tile-footer tooltip-button">
                                        view details
                                        <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="@Url.Action("Index", "ProgramExecutionMonitor")" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-purple">
                                <div class="tile-header">
                                    virtual HMI
                                </div>
                                <div class="tile-content-wrapper">

                                    <img src="~/images/part-entry.png" />
                                </div>

                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>

                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="@Url.Action("Index", "ProgramTransfer")" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-azure">
                                <div class="tile-header">
                                    NC Program Transfer
                                </div>
                                <div class="tile-content-wrapper">

                                    <img src="~/images/email.png" />
                                </div>

                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>

                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="#" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-green">
                                <div class="tile-header">
                                    Reports
                                </div>
                                <div class="tile-content-wrapper">

                                    <img src="~/images/reports.png" />
                                </div>

                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>

                            </div>
                        </a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-3">
                        <a href="@Url.Action("MachineList", "Machines")" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-black-opacity">
                                <div class="tile-header">
                                    Machine Management
                                </div>
                                <div class="tile-content-wrapper">
                                    <img src="~/images/machine.png" />
                                </div>
                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="@Url.Action("Index", "ProductionLoss")" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-orange">
                                <div class="tile-header">
                                    Losses & Breakdown Configuration
                                </div>
                                <div class="tile-content-wrapper">
                                    <img src="~/images/losses.png" />
                                </div>
                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="@Url.Action("Index", "Roles")" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-danger">
                                <div class="tile-header">
                                    Role Configuration
                                </div>
                                <div class="tile-content-wrapper">
                                    <img src="~/images/roles.png" />
                                </div>
                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="@Url.Action("Index", "PartsManagement")" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-brown">
                                <div class="tile-header">
                                    General Configuration
                                </div>
                                <div class="tile-content-wrapper">
                                    <img src="~/images/general.png" />
                                </div>
                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <a href="@Url.Action("Calendar", "Calendar")" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-parrot" style="color: #fff;border-color: #D500F9;background:#D500F9;">
                                <div class="tile-header">
                                    Holiday Managment
                                </div>
                                <div class="tile-content-wrapper">
                                    <img src="~/images/calendar.png" />
                                </div>
                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-3">
                        <a href="@Url.Action("UserManagement", "User")" data-placement="bottom">
                            <div class="tile-box tile-box-alt bg-parrot" style="color: #fff;border-color: #F535AA;background:#F535AA;">
                                <div class="tile-header">
                                    User Management
                                </div>
                                <div class="tile-content-wrapper">
                                    <img src="~/images/User-Management.png" />
                                </div>
                                <div class="tile-footer tooltip-button">
                                    view details
                                    <i class="fa fa-arrow-right glyph-icon" aria-hidden="true"></i>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>*@
        </div>
    </div>
</div>
<!-- /page content -->

<script src="~/vendors/jquery/dist/jquery.min.js"></script>
<script src="~/Scripts/MCAdmin/Dashboard.js"></script>