UnitWorksCCS/Controllers/AutomaticEmailReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnitWorksCCS.ServerModels;
using System.Data.Entity;
using System.Globalization;

namespace UnitWorksCCS.Controllers
{
    public class AutomaticEmailReportController : Controller
    {
        i_facility_talEntities db = new i_facility_talEntities();
        public ActionResult Index()
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            Session["Error"] = null;
            var Escalationdata = db.tbl_autoreportsetting.Where(m => m.IsDeleted == 0).ToList();
            return View(Escalationdata);
        }

        public ActionResult Create()
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();

            ViewBag.RL1 = new SelectList(db.tbl_reportmaster.Where(m => m.IsDeleted == 0), "ReportID", "ReportDispName");
            ViewBag.RL2 = new SelectList(db.tbl_autoreportbasedon.Where(m => m.IsDeleted == 0), "BasedOnID", "BasedOn");
            ViewBag.RL3 = new SelectList(db.tbl_autoreporttime.Where(m => m.IsDeleted == 0), "AutoReportTimeID", "AutoReportTime");
            ViewBag.Plant = new SelectList(db.tblplants.Where(m => m.IsDeleted == 0), "PlantID", "PlantName");
            ViewBag.Shop = new SelectList(db.tblshops.Where(m => m.IsDeleted == 0 && m.PlantID == 1), "ShopID", "ShopName");
            ViewBag.Cell = new SelectList(db.tblcells.Where(m => m.IsDeleted == 0 && m.PlantID == 999), "CellID", "CellName");
            ViewBag.WorkCenter = new SelectList(db.tblmachinedetails.Where(m => m.IsDeleted == 0 && m.IsNormalWC == 0 && m.PlantID == 999), "MachineID", "MachineInvNo");

            return View();
        }
        [HttpPost]
        public ActionResult Create(tbl_autoreportsetting tee)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            #region//ActiveLog Code
            int UserID = Convert.ToInt32(Session["UserId"]);
            //string CompleteModificationdetail = "New Creation";
            //Action = "Create";
            // ActiveLogStorage Obj = new ActiveLogStorage();
            // Obj.SaveActiveLog(Action, Controller, Username, UserID, CompleteModificationdetail);
            //End
            #endregion

            //Email validation
            string RL1 = Convert.ToString(tee.ReportID);
            string RL2 = Convert.ToString(tee.BasedOn);
            string RL3 = Convert.ToString(tee.AutoReportTimeID);
            string ValidEscalation = null;

            //ValidEscalation = IsItValidEscalation(RL1, RL2, RL3);


            if (tee.AutoReportTimeID == 1) //day
            {
                tee.NextRunDate = DateTime.Now.AddDays(1);
            }
            else if (tee.AutoReportTimeID == 2) //week
            {
                DateTime begining, end;
                GetWeek(DateTime.Now, new CultureInfo("fr-FR"), out begining, out end);
                tee.NextRunDate = end.AddDays(1);
            }
            else if (tee.AutoReportTimeID == 3) //month
            {
                DateTime Temp2 = new DateTime(DateTime.Now.Year, DateTime.Now.AddMonths(1).Month, 01, 00, 00, 01);
                tee.NextRunDate = Temp2;
            }
            else if (tee.AutoReportTimeID == 4) //year
            {
                DateTime Temp2 = new DateTime(DateTime.Now.AddYears(1).Year, 01, 01, 00, 00, 01);
                tee.NextRunDate = Temp2;
            }

            var DupData = db.tbl_autoreportsetting.Where(m =>m.IsDeleted==0 && m.ReportID == tee.ReportID && m.BasedOn == tee.BasedOn && m.AutoReportTimeID == tee.AutoReportTimeID && m.PlantID == tee.PlantID && m.ShopID == tee.ShopID && m.CellID == tee.CellID && m.MachineID == tee.MachineID).FirstOrDefault();
            if (DupData != null)
            {
                ValidEscalation += " Duplicate Entry ";
                TempData["toaster_error"] = ValidEscalation;
            }
            if (ValidEscalation == null)
            {
                tee.CreatedBy = UserID;
                tee.CreatedOn = DateTime.Now;
                tee.IsDeleted = 0;

                db.tbl_autoreportsetting.Add(tee);
                db.SaveChanges();
            }
            else
            {
                Session["Error"] = ValidEscalation;
                TempData["toaster_error"] = ValidEscalation;
                ViewBag.RL1 = new SelectList(db.tbl_reportmaster.Where(m => m.IsDeleted == 0), "ReportID", "ReportDispName", tee.ReportID);
                ViewBag.RL2 = new SelectList(db.tbl_autoreportbasedon.Where(m => m.IsDeleted == 0), "BasedOnID", "BasedOn", tee.BasedOn);
                ViewBag.RL3 = new SelectList(db.tbl_autoreporttime.Where(m => m.IsDeleted == 0), "AutoReportTimeID", "AutoReportTime", tee.AutoReportTimeID);

                ViewBag.Plant = new SelectList(db.tblplants.Where(m => m.IsDeleted == 0), "PlantID", "PlantName", tee.PlantID);
                ViewBag.Shop = new SelectList(db.tblshops.Where(m => m.IsDeleted == 0 && m.PlantID == tee.PlantID), "ShopID", "ShopName", tee.ShopID);
                ViewBag.Cell = new SelectList(db.tblcells.Where(m => m.IsDeleted == 0 && m.PlantID == tee.ShopID), "CellID", "CellName", tee.CellID);
                ViewBag.WorkCenter = new SelectList(db.tblmachinedetails.Where(m => m.IsDeleted == 0 && m.IsNormalWC == 0 && m.PlantID == tee.PlantID && m.ShopID == tee.ShopID && m.CellID == tee.CellID), "MachineID", "MachineDisplayName", tee.MachineID);

                return View(tee);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            tbl_autoreportsetting tee = db.tbl_autoreportsetting.Find(id);
            ViewBag.RL1 = new SelectList(db.tbl_reportmaster.Where(m => m.IsDeleted == 0), "ReportID", "ReportDispName", tee.ReportID);
            ViewBag.RL2 = new SelectList(db.tbl_autoreportbasedon.Where(m => m.IsDeleted == 0), "BasedOnID", "BasedOn", tee.BasedOn);
            ViewBag.RL3 = new SelectList(db.tbl_autoreporttime.Where(m => m.IsDeleted == 0), "AutoReportTimeID", "AutoReportTime", tee.AutoReportTimeID);
            ViewBag.Plant = new SelectList(db.tblplants.Where(m => m.IsDeleted == 0), "PlantID", "PlantName", tee.PlantID);
            ViewBag.Shop = new SelectList(db.tblshops.Where(m => m.IsDeleted == 0 && m.PlantID == tee.PlantID), "ShopID", "ShopName", tee.ShopID);
            ViewBag.Cell = new SelectList(db.tblcells.Where(m => m.IsDeleted == 0 && m.ShopID == tee.ShopID), "CellID", "CellName", tee.CellID);
            ViewBag.WorkCenter = new SelectList(db.tblmachinedetails.Where(m => m.IsDeleted == 0 && m.PlantID == tee.PlantID && m.ShopID == tee.ShopID && m.CellID == tee.CellID), "MachineID", "MachineDisplayName", tee.MachineID);
            return View(tee);
        }
        [HttpPost]
        public ActionResult Edit(tbl_autoreportsetting tee)
        {
            if ((Session["UserId"] == null) || (Session["UserId"].ToString() == String.Empty))
            {
                return RedirectToAction("Login", "Login", null);
            }
            ViewBag.Logout = Session["Username"].ToString().ToUpper();
            ViewBag.roleid = Session["RoleID"];
            String Username = Session["Username"].ToString();
            #region//ActiveLog Code
            int UserID = Convert.ToInt32(Session["UserId"]);
            //string CompleteModificationdetail = "New Creation";
            //Action = "Create";
            // ActiveLogStorage Obj = new ActiveLogStorage();
            // Obj.SaveActiveLog(Action, Controller, Username, UserID, CompleteModificationdetail);
            //End
            #endregion

            //Email validation
            string RL1 = Convert.ToString(tee.ReportID);
            string RL2 = Convert.ToString(tee.BasedOn);
            string RL3 = Convert.ToString(tee.AutoReportTimeID);
            string ValidEscalation = null;

            //ValidEscalation = IsItValidEscalation(RL1, RL2, RL3);

            if (tee.AutoReportTimeID == 1) //day
            {
                tee.NextRunDate = DateTime.Now.AddDays(1);
            }
            else if (tee.AutoReportTimeID == 2) //week
            {
                DateTime begining, end;
                GetWeek(DateTime.Now, new CultureInfo("fr-FR"), out begining, out end);
                tee.NextRunDate = end.AddDays(1);
            }
            else if (tee.AutoReportTimeID == 3) //month
            {
                DateTime Temp2 = new DateTime(DateTime.Now.Year, DateTime.Now.AddMonths(1).Month, 01, 00, 00, 01);
                tee.NextRunDate = Temp2;
            }
            else if (tee.AutoReportTimeID == 4) //year
            {

UnitWorksCCS/Views/AutomaticEmailReport/Copy.cshtml
@model UnitWorksCCS.tbl_autoreportsetting
@{
    ViewBag.Title = "Copy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="right_col" role="main">
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
@using (Html.BeginForm("Copy", "AutomaticEmailReport", FormMethod.Post))
{
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Copy Automatic Report</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <form class="form-horizontal form-label-left" novalidate>
                            <div class="row form-horizontal">
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Report</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.ReportID, ViewBag.RL1 as IEnumerable<SelectListItem>, "--Select Report--", new { @id = "RL1", @class = "form-control", @name = "RL1", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.ReportID)
                                    </div>
                                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Based On</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.BasedOn, ViewBag.RL2 as IEnumerable<SelectListItem>, "--Select Based On--", new { @id = "RL2", @class = "form-control", @name = "RL2", @tabindex = "2", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.BasedOn)
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Time</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.AutoReportTimeID, ViewBag.RL3 as IEnumerable<SelectListItem>, "--Select Report Time--", new { @id = "RL3", @class = "form-control", @tabindex = "2", @name = "RL3", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.AutoReportTimeID)
                                    </div>
                                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Plant</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.PlantID, ViewBag.Plant as IEnumerable<SelectListItem>, "--Select Plant--", new { @id = "PlantID", @class = "form-control", @tabindex = "2", @name = "PlantID", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.PlantID)
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Shop</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.ShopID, ViewBag.Shop as IEnumerable<SelectListItem>, "--Select Shop--", new { @id = "ShopID", @class = "form-control", @tabindex = "2", @name = "ShopID", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.ShopID)
                                    </div>
                                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Cell</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.CellID, ViewBag.Cell as IEnumerable<SelectListItem>, "--Select Cell--", new { @id = "MachineCategoryID", @class = "form-control1", @tabindex = "2", @name = "MachineCategoryID" })
                                        @Html.ValidationMessageFor(model => model.CellID)
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12 adjust-label">Machine Inv No.</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.MachineID, ViewBag.WorkCenter as IEnumerable<SelectListItem>, "--Select Machine--", new { @id = "MachineID", @class = "form-control", @tabindex = "2", @name = "MachineID" })
                                        @Html.ValidationMessageFor(model => model.MachineID)
                                    </div>
                                    <label class="control-label col-md-2 col-sm-3 col-xs-12">To List</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.TextAreaFor(model => model.ToMailList, new { @class = "form-control1" })
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12">CC List</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.TextAreaFor(model => model.CCMailList, new { @class = "form-control1", @stye = "margin - top: -15px;" })
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                @Html.HiddenFor(Model => Model.AutoReportID)
                @Html.HiddenFor(Model => Model.CreatedBy)
                @Html.HiddenFor(Model => Model.CreatedOn)
                @Html.HiddenFor(Model => Model.IsDeleted)
                @Html.HiddenFor(Model => Model.NextRunDate)
                <a role="button" href="@Url.Action("Index", "AutomaticEmailReport")"  class="btn btn-new" style="margin-top: 10px; margin-left: 5px;"><i class="fa fa-chevron-left" aria-hidden="true"></i>&nbsp;Back</a>
                <button type="submit" class="btn btn-new float-right" style="margin-top: 10px;"><i class="fa fa-floppy-o" aria-hidden="true"></i>&nbsp;Save</button>
             
            </div>
     }
        </div>
    </div>
</div>

<script src="~/js/jquery-2.1.4.min.js"></script>
<script src="~/vendors/fastclick/lib/fastclick.js"></script>
<script src="~/js/bootstrap.min.js"></script>

<script>

    //Cascading
    $("#PlantID").on("change", function () {
        $("#ShopID").empty();
        $("#CellID").empty();
        $("#MachineID").empty();
        var selectedID = $("#PlantID option:selected").val();
        $.getJSON("/ShiftPlanner/GetShop", { PlantID: selectedID }, function (data) {
            $.each(data, function (index, item) {
                $("#ShopID").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
                //$("#CellID").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
            });
            $("#ShopID").prepend("<option value='' selected='selected'></option>");
            $("#MachineID").prepend("<option value='' selected='selected'></option>");
        });
    });

    $("#ShopID").on("change", function () {
        $("#MachineCategoryID").empty();
        $("#MachineID").empty();
        var selectedID = $("#ShopID option:selected").val();
        $.getJSON("/ShiftPlanner/GetCell", { ShopID: selectedID }, function (data) {
            $.each(data, function (index, item) {
                $("#MachineCategoryID").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
            });
            $("#MachineCategoryID").prepend("<option value='' selected='selected'></option>");
        });



    });

    $("#MachineCategoryID").on("change", function () {
        $("#MachineID").empty();
        var selectedID = $("#MachineCategoryID option:selected").val();
        //alert(selectedID);
        $.getJSON("/ShiftPlanner/GetWC_Cell", { CellID: selectedID }, function (data) {
            $.each(data, function (index, item) {
                $("#MachineID").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
            });
            $("#MachineID").prepend("<option value='' selected='selected'></option>");

        });
    });
</script>
<script>
    function ChangeBasedOn() {
        var item = $("#RL2 option:selected").text();
        if (item == "Plant") {
            $("#PlantID").attr("required", "required");
            $("#ShopID").removeAttr("required", "required");
            $("#MachineCategoryID").removeAttr("required", "required");
            $("#MachineID").removeAttr("required", "required");
        } else if (item == "Shop") {
            $("#PlantID").attr("required", "required");
            $("#ShopID").attr("required", "required");
            $("#MachineCategoryID").removeAttr("required", "required");
            $("#MachineID").removeAttr("required", "required");

        } else if (item == "Cell") {
            $("#PlantID").attr("required", "required");
            $("#ShopID").attr("required", "required");
            $("#MachineCategoryID").attr("required", "required");
            $("#MachineID").removeAttr("required", "required");

        } else if (item == "Machine") {
            $("#PlantID").attr("required", "required");
            $("#ShopID").attr("required", "required");
            $("#MachineCategoryID").attr("required", "required");
            $("#MachineID").attr("required", "required");
        } else {
            $("#PlantID").attr("required", "required");
            $("#ShopID").attr("required", "required");
            $("#MachineCategoryID").attr("required", "required");
            $("#MachineID").attr("required", "required");
        }
    }
</script>

UnitWorksCCS/Views/AutomaticEmailReport/Edit.cshtml
@model UnitWorksCCS.tbl_autoreportsetting
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="right_col" role="main">
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
@using (Html.BeginForm("Edit", "AutomaticEmailReport", FormMethod.Post))
{
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Edit Automatic Report</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                   
                    <div class="x_content">
                        <form class="form-horizontal form-label-left" novalidate>
                            <div class="row form-horizontal">
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Report</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.ReportID, ViewBag.RL1 as IEnumerable<SelectListItem>, "--Select Report--", new { @id = "RL1", @class = "form-control", @name = "RL1", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.ReportID)
                                    </div>
                                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Based On</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.BasedOn, ViewBag.RL2 as IEnumerable<SelectListItem>, "--Select Based On--", new { @id = "RL2", @class = "form-control", @name = "RL2", @tabindex = "2", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.BasedOn)
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Time</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.AutoReportTimeID, ViewBag.RL3 as IEnumerable<SelectListItem>, "--Select Report Time--", new { @id = "RL3", @class = "form-control", @tabindex = "2", @name = "RL3", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.AutoReportTimeID)
                                    </div>
                                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Plant</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.PlantID, ViewBag.Plant as IEnumerable<SelectListItem>, "--Select Plant--", new { @id = "PlantID", @class = "form-control", @tabindex = "2", @name = "PlantID", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.PlantID)
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12">Shop</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.ShopID, ViewBag.Shop as IEnumerable<SelectListItem>, "--Select Shop--", new { @id = "ShopID", @class = "form-control", @tabindex = "2", @name = "ShopID", @required = "required" })
                                        @Html.ValidationMessageFor(model => model.ShopID)
                                    </div>
                                    <label class="control-label col-md-2 col-sm-3 col-xs-12">Cell</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.CellID, ViewBag.Cell as IEnumerable<SelectListItem>, "--Select Cell--", new { @id = "MachineCategoryID", @class = "form-control1", @tabindex = "2", @name = "MachineCategoryID" })
                                        @Html.ValidationMessageFor(model => model.CellID)
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12 adjust-label">Machine Inv No.</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.DropDownListFor(model => model.MachineID, ViewBag.WorkCenter as IEnumerable<SelectListItem>, "--Select Machine--", new { @id = "MachineID", @class = "form-control", @tabindex = "2", @name = "MachineID" })
                                        @Html.ValidationMessageFor(model => model.MachineID)
                                    </div>
                                    <label class="control-label col-md-2 col-sm-3 col-xs-12">To List</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.TextAreaFor(model => model.ToMailList, new { @class = "form-control1" })
                                    </div>
                                </div>
                                <div class="item form-group">
                                    <label class="control-label col-md-1 col-sm-3 col-xs-12">CC List</label>
                                    <div class="col-md-4 col-sm-6 col-xs-12">
                                        @Html.TextAreaFor(model => model.CCMailList, new { @class = "form-control1", @stye = "margin - top: -15px;" })
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
                @Html.HiddenFor(Model => Model.AutoReportID)
                @Html.HiddenFor(Model => Model.CreatedBy)
                @Html.HiddenFor(Model => Model.CreatedOn)
                @Html.HiddenFor(Model => Model.IsDeleted)
                @Html.HiddenFor(Model => Model.NextRunDate)
                <a role="button" href="@Url.Action("Index", "AutomaticEmailReport")" class="btn btn-new" style="margin-top: 10px; margin-left: 5px;"><i class="fa fa-chevron-left" aria-hidden="true"></i>&nbsp;Back</a>
                <button type="submit" class="btn btn-new float-right" style="margin-top: 10px;"><i class="fa fa-floppy-o" aria-hidden="true"></i>&nbsp;Save</button>

            </div>
              }
        </div>
    </div>
</div>


<script src="~/js/jquery-2.1.4.min.js"></script>
<script src="~/vendors/fastclick/lib/fastclick.js"></script>
<script src="~/js/bootstrap.min.js"></script>

<script>

    //Cascading
    $("#PlantID").on("change", function () {
        $("#ShopID").empty();
        $("#CellID").empty();
        $("#MachineID").empty();
        var selectedID = $("#PlantID option:selected").val();
        $.getJSON("/ShiftPlanner/GetShop", { PlantID: selectedID }, function (data) {
            $.each(data, function (index, item) {
                $("#ShopID").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
                //$("#CellID").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
            });
            $("#ShopID").prepend("<option value='' selected='selected'></option>");
            $("#MachineID").prepend("<option value='' selected='selected'></option>");
        });
    });

    $("#ShopID").on("change", function () {
        $("#MachineCategoryID").empty();
        $("#MachineID").empty();
        var selectedID = $("#ShopID option:selected").val();
        $.getJSON("/ShiftPlanner/GetCell", { ShopID: selectedID }, function (data) {
            $.each(data, function (index, item) {
                $("#MachineCategoryID").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
            });
            $("#MachineCategoryID").prepend("<option value='' selected='selected'></option>");
        });



    });

    $("#MachineCategoryID").on("change", function () {
        $("#MachineID").empty();
        var selectedID = $("#MachineCategoryID option:selected").val();
        alert(selectedID);
        $.getJSON("/ShiftPlanner/GetWC_Cell", { CellID: selectedID }, function (data) {
            $.each(data, function (index, item) {
                $("#MachineID").append("<option value='" + item.Value + "'>" + item.Text + "</option>");
            });
            $("#MachineID").prepend("<option value='' selected='selected'></option>");

        });
    });
</script>

<script>
    function ChangeBasedOn() {
        var item = $("#RL2 option:selected").text();
        if (item == "Plant") {
            $("#PlantID").attr("required", "required");
            $("#ShopID").removeAttr("required", "required");
            $("#MachineCategoryID").removeAttr("required", "required");
            $("#MachineID").removeAttr("required", "required");
        } else if (item == "Shop") {
            $("#PlantID").attr("required", "required");
            $("#ShopID").attr("required", "required");
            $("#MachineCategoryID").removeAttr("required", "required");
            $("#MachineID").removeAttr("required", "required");

        } else if (item == "Cell") {
            $("#PlantID").attr("required", "required");
            $("#ShopID").attr("required", "required");
            $("#MachineCategoryID").attr("required", "required");
            $("#MachineID").removeAttr("required", "required");

        } else if (item == "Machine") {
            $("#PlantID").attr("required", "required");
            $("#ShopID").attr("required", "required");
            $("#MachineCategoryID").attr("required", "required");
            $("#MachineID").attr("required", "required");
        } else {
            $("#PlantID").attr("required", "required");
            $("#ShopID").attr("required", "required");
            $("#MachineCategoryID").attr("required", "required");
            $("#MachineID").attr("required", "required");
        }
    }
</script>